// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/metatable/branch.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Branch service

type BranchService interface {
	// 导入YAML
	ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error)
	// 列举
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*BranchListResponse, error)
	// 删除
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error)
}

type branchService struct {
	c    client.Client
	name string
}

func NewBranchService(name string, c client.Client) BranchService {
	return &branchService{
		c:    c,
		name: name,
	}
}

func (c *branchService) ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Branch.ImportYaml", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*BranchListResponse, error) {
	req := c.c.NewRequest(c.name, "Branch.List", in)
	out := new(BranchListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Branch.Delete", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Branch service

type BranchHandler interface {
	// 导入YAML
	ImportYaml(context.Context, *ImportYamlRequest, *BlankResponse) error
	// 列举
	List(context.Context, *ListRequest, *BranchListResponse) error
	// 删除
	Delete(context.Context, *DeleteRequest, *BlankResponse) error
}

func RegisterBranchHandler(s server.Server, hdlr BranchHandler, opts ...server.HandlerOption) error {
	type branch interface {
		ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error
		List(ctx context.Context, in *ListRequest, out *BranchListResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error
	}
	type Branch struct {
		branch
	}
	h := &branchHandler{hdlr}
	return s.Handle(s.NewHandler(&Branch{h}, opts...))
}

type branchHandler struct {
	BranchHandler
}

func (h *branchHandler) ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error {
	return h.BranchHandler.ImportYaml(ctx, in, out)
}

func (h *branchHandler) List(ctx context.Context, in *ListRequest, out *BranchListResponse) error {
	return h.BranchHandler.List(ctx, in, out)
}

func (h *branchHandler) Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error {
	return h.BranchHandler.Delete(ctx, in, out)
}
