// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metatable/branch.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 合并实体
type MergeEntity struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 []string `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeEntity) Reset()         { *m = MergeEntity{} }
func (m *MergeEntity) String() string { return proto.CompactTextString(m) }
func (*MergeEntity) ProtoMessage()    {}
func (*MergeEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_148af82c881d017c, []int{0}
}

func (m *MergeEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeEntity.Unmarshal(m, b)
}
func (m *MergeEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeEntity.Marshal(b, m, deterministic)
}
func (m *MergeEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeEntity.Merge(m, src)
}
func (m *MergeEntity) XXX_Size() int {
	return xxx_messageInfo_MergeEntity.Size(m)
}
func (m *MergeEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeEntity.DiscardUnknown(m)
}

var xxx_messageInfo_MergeEntity proto.InternalMessageInfo

func (m *MergeEntity) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MergeEntity) GetFrom() []string {
	if m != nil {
		return m.From
	}
	return nil
}

// 分支实体
type BranchEntity struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Merge                *MergeEntity `protobuf:"bytes,3,opt,name=merge,proto3" json:"merge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BranchEntity) Reset()         { *m = BranchEntity{} }
func (m *BranchEntity) String() string { return proto.CompactTextString(m) }
func (*BranchEntity) ProtoMessage()    {}
func (*BranchEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_148af82c881d017c, []int{1}
}

func (m *BranchEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchEntity.Unmarshal(m, b)
}
func (m *BranchEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchEntity.Marshal(b, m, deterministic)
}
func (m *BranchEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchEntity.Merge(m, src)
}
func (m *BranchEntity) XXX_Size() int {
	return xxx_messageInfo_BranchEntity.Size(m)
}
func (m *BranchEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BranchEntity proto.InternalMessageInfo

func (m *BranchEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BranchEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BranchEntity) GetMerge() *MergeEntity {
	if m != nil {
		return m.Merge
	}
	return nil
}

type BranchListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*BranchEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BranchListResponse) Reset()         { *m = BranchListResponse{} }
func (m *BranchListResponse) String() string { return proto.CompactTextString(m) }
func (*BranchListResponse) ProtoMessage()    {}
func (*BranchListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_148af82c881d017c, []int{2}
}

func (m *BranchListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchListResponse.Unmarshal(m, b)
}
func (m *BranchListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchListResponse.Marshal(b, m, deterministic)
}
func (m *BranchListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchListResponse.Merge(m, src)
}
func (m *BranchListResponse) XXX_Size() int {
	return xxx_messageInfo_BranchListResponse.Size(m)
}
func (m *BranchListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BranchListResponse proto.InternalMessageInfo

func (m *BranchListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BranchListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BranchListResponse) GetEntity() []*BranchEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*MergeEntity)(nil), "metatable.MergeEntity")
	proto.RegisterType((*BranchEntity)(nil), "metatable.BranchEntity")
	proto.RegisterType((*BranchListResponse)(nil), "metatable.BranchListResponse")
}

func init() {
	proto.RegisterFile("proto/metatable/branch.proto", fileDescriptor_148af82c881d017c)
}

var fileDescriptor_148af82c881d017c = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x92, 0x36, 0xd0, 0x89, 0x08, 0x0e, 0xa2, 0xa1, 0x54, 0x08, 0x39, 0x45, 0x90, 0x16,
	0xe3, 0x5d, 0x41, 0x54, 0x10, 0xf4, 0xb2, 0x9e, 0x3c, 0x6e, 0xed, 0x68, 0x8b, 0x49, 0xb6, 0xee,
	0x4e, 0x0e, 0xfe, 0x80, 0xff, 0xe7, 0x1f, 0x49, 0x76, 0x63, 0x5d, 0xe8, 0xc5, 0xdb, 0xe4, 0xed,
	0x7b, 0xf3, 0xde, 0x9b, 0xc0, 0x74, 0xa3, 0x15, 0xab, 0x79, 0x4d, 0x2c, 0x59, 0x2e, 0x2a, 0x9a,
	0x2f, 0xb4, 0x6c, 0x5e, 0x56, 0x33, 0x0b, 0xe3, 0x78, 0x8b, 0x4f, 0x76, 0x88, 0x66, 0x25, 0x35,
	0x2d, 0x1d, 0x31, 0x3f, 0x87, 0xe4, 0x91, 0xf4, 0x1b, 0xdd, 0x36, 0xbc, 0xe6, 0x4f, 0xdc, 0x87,
	0x90, 0x55, 0x1a, 0x64, 0x41, 0x31, 0x16, 0x21, 0x2b, 0x44, 0x18, 0xbe, 0x6a, 0x55, 0xa7, 0x61,
	0x16, 0x15, 0x63, 0x61, 0xe7, 0x7c, 0x09, 0x7b, 0xd7, 0xd6, 0xab, 0xd7, 0x20, 0x0c, 0xdb, 0x76,
	0xbd, 0xec, 0x55, 0x76, 0xee, 0xb0, 0x46, 0xd6, 0x94, 0x86, 0x0e, 0xeb, 0x66, 0x3c, 0x83, 0x51,
	0xdd, 0x59, 0xa5, 0x51, 0x16, 0x14, 0x49, 0x79, 0x34, 0xdb, 0x46, 0x9a, 0x79, 0x11, 0x84, 0x23,
	0xe5, 0x5f, 0x01, 0xa0, 0xb3, 0x79, 0x58, 0x1b, 0x16, 0x64, 0x36, 0xaa, 0x31, 0x84, 0xa7, 0x10,
	0x1b, 0x96, 0xdc, 0x1a, 0x6b, 0x97, 0x94, 0x07, 0xde, 0x96, 0x27, 0xfb, 0x20, 0x7a, 0x02, 0x1e,
	0xc2, 0x88, 0x15, 0xcb, 0xca, 0x86, 0x88, 0x84, 0xfb, 0xc0, 0x39, 0xc4, 0x64, 0x8d, 0xd2, 0x28,
	0x8b, 0x8a, 0xa4, 0x3c, 0xf6, 0x16, 0xf8, 0xb5, 0x44, 0x4f, 0x2b, 0xbf, 0x03, 0x88, 0xdd, 0x03,
	0xde, 0x01, 0xdc, 0xd7, 0x1b, 0xa5, 0xf9, 0x59, 0xd6, 0x15, 0x4e, 0x3d, 0xe5, 0x1f, 0x2c, 0xe8,
	0xa3, 0x25, 0xc3, 0x93, 0xd4, 0xdf, 0x5b, 0xc9, 0xe6, 0xfd, 0xb7, 0x42, 0x3e, 0xc0, 0x2b, 0x18,
	0x76, 0xa5, 0xd0, 0x3f, 0x81, 0x6b, 0xe9, 0xb4, 0x27, 0x3b, 0x99, 0xfc, 0x1b, 0xe4, 0x03, 0xbc,
	0x84, 0xf8, 0x86, 0x2a, 0x62, 0x42, 0xdf, 0xc6, 0x41, 0xff, 0x08, 0xb0, 0x88, 0xed, 0xcf, 0xbf,
	0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xad, 0x07, 0xa0, 0x45, 0x02, 0x00, 0x00,
}
