// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/metatable/format.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Format service

type FormatService interface {
	// 导入YAML
	ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error)
	// 列举
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*FormatListResponse, error)
	// 删除
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error)
}

type formatService struct {
	c    client.Client
	name string
}

func NewFormatService(name string, c client.Client) FormatService {
	return &formatService{
		c:    c,
		name: name,
	}
}

func (c *formatService) ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Format.ImportYaml", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*FormatListResponse, error) {
	req := c.c.NewRequest(c.name, "Format.List", in)
	out := new(FormatListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formatService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Format.Delete", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Format service

type FormatHandler interface {
	// 导入YAML
	ImportYaml(context.Context, *ImportYamlRequest, *BlankResponse) error
	// 列举
	List(context.Context, *ListRequest, *FormatListResponse) error
	// 删除
	Delete(context.Context, *DeleteRequest, *BlankResponse) error
}

func RegisterFormatHandler(s server.Server, hdlr FormatHandler, opts ...server.HandlerOption) error {
	type format interface {
		ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error
		List(ctx context.Context, in *ListRequest, out *FormatListResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error
	}
	type Format struct {
		format
	}
	h := &formatHandler{hdlr}
	return s.Handle(s.NewHandler(&Format{h}, opts...))
}

type formatHandler struct {
	FormatHandler
}

func (h *formatHandler) ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error {
	return h.FormatHandler.ImportYaml(ctx, in, out)
}

func (h *formatHandler) List(ctx context.Context, in *ListRequest, out *FormatListResponse) error {
	return h.FormatHandler.List(ctx, in, out)
}

func (h *formatHandler) Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error {
	return h.FormatHandler.Delete(ctx, in, out)
}
