// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metatable/format.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 模式实体
type PatternEntity struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 []string `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatternEntity) Reset()         { *m = PatternEntity{} }
func (m *PatternEntity) String() string { return proto.CompactTextString(m) }
func (*PatternEntity) ProtoMessage()    {}
func (*PatternEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a4705749b5b6290, []int{0}
}

func (m *PatternEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatternEntity.Unmarshal(m, b)
}
func (m *PatternEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatternEntity.Marshal(b, m, deterministic)
}
func (m *PatternEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatternEntity.Merge(m, src)
}
func (m *PatternEntity) XXX_Size() int {
	return xxx_messageInfo_PatternEntity.Size(m)
}
func (m *PatternEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_PatternEntity.DiscardUnknown(m)
}

var xxx_messageInfo_PatternEntity proto.InternalMessageInfo

func (m *PatternEntity) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PatternEntity) GetFrom() []string {
	if m != nil {
		return m.From
	}
	return nil
}

// 格式实体
type FormatEntity struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pattern              []*PatternEntity `protobuf:"bytes,3,rep,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FormatEntity) Reset()         { *m = FormatEntity{} }
func (m *FormatEntity) String() string { return proto.CompactTextString(m) }
func (*FormatEntity) ProtoMessage()    {}
func (*FormatEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a4705749b5b6290, []int{1}
}

func (m *FormatEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatEntity.Unmarshal(m, b)
}
func (m *FormatEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatEntity.Marshal(b, m, deterministic)
}
func (m *FormatEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatEntity.Merge(m, src)
}
func (m *FormatEntity) XXX_Size() int {
	return xxx_messageInfo_FormatEntity.Size(m)
}
func (m *FormatEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatEntity.DiscardUnknown(m)
}

var xxx_messageInfo_FormatEntity proto.InternalMessageInfo

func (m *FormatEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *FormatEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FormatEntity) GetPattern() []*PatternEntity {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type FormatListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*FormatEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FormatListResponse) Reset()         { *m = FormatListResponse{} }
func (m *FormatListResponse) String() string { return proto.CompactTextString(m) }
func (*FormatListResponse) ProtoMessage()    {}
func (*FormatListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a4705749b5b6290, []int{2}
}

func (m *FormatListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormatListResponse.Unmarshal(m, b)
}
func (m *FormatListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormatListResponse.Marshal(b, m, deterministic)
}
func (m *FormatListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormatListResponse.Merge(m, src)
}
func (m *FormatListResponse) XXX_Size() int {
	return xxx_messageInfo_FormatListResponse.Size(m)
}
func (m *FormatListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FormatListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FormatListResponse proto.InternalMessageInfo

func (m *FormatListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *FormatListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *FormatListResponse) GetEntity() []*FormatEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*PatternEntity)(nil), "metatable.PatternEntity")
	proto.RegisterType((*FormatEntity)(nil), "metatable.FormatEntity")
	proto.RegisterType((*FormatListResponse)(nil), "metatable.FormatListResponse")
}

func init() {
	proto.RegisterFile("proto/metatable/format.proto", fileDescriptor_0a4705749b5b6290)
}

var fileDescriptor_0a4705749b5b6290 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x92, 0x1a, 0xe9, 0x54, 0x05, 0x07, 0xd1, 0x50, 0x2a, 0x94, 0x9c, 0xea, 0xa5, 0x85,
	0xf4, 0xae, 0x20, 0x5a, 0x10, 0x3c, 0xc8, 0x7a, 0xf2, 0xb8, 0xa5, 0x53, 0xac, 0x66, 0xb3, 0x71,
	0x77, 0x72, 0xf0, 0x07, 0xfc, 0x3f, 0xff, 0x48, 0xba, 0x9b, 0xd6, 0x95, 0x5e, 0xbc, 0x4d, 0xde,
	0xbc, 0x37, 0xef, 0xbd, 0xb0, 0x30, 0xac, 0x8d, 0x66, 0x3d, 0x55, 0xc4, 0x92, 0xe5, 0xa2, 0xa4,
	0xe9, 0x4a, 0x1b, 0x25, 0x79, 0xe2, 0x60, 0xec, 0xed, 0xf0, 0xc1, 0x1e, 0xd1, 0xbe, 0x4a, 0x43,
	0x4b, 0x4f, 0xcc, 0x67, 0x70, 0xfc, 0x24, 0x99, 0xc9, 0x54, 0xf7, 0x15, 0xaf, 0xf9, 0x13, 0x4f,
	0x20, 0x66, 0x9d, 0x45, 0xa3, 0x68, 0xdc, 0x13, 0x31, 0x6b, 0x44, 0xe8, 0xae, 0x8c, 0x56, 0x59,
	0x3c, 0x4a, 0xc6, 0x3d, 0xe1, 0xe6, 0xfc, 0x0d, 0x8e, 0xe6, 0xce, 0xad, 0xd5, 0x20, 0x74, 0x9b,
	0x66, 0xbd, 0x6c, 0x55, 0x6e, 0xde, 0x60, 0x95, 0x54, 0x94, 0xc5, 0x1e, 0xdb, 0xcc, 0x58, 0xc0,
	0x61, 0xed, 0xcd, 0xb2, 0x64, 0x94, 0x8c, 0xfb, 0x45, 0x36, 0xd9, 0xc5, 0x9a, 0xfc, 0x89, 0x21,
	0xb6, 0xc4, 0xfc, 0x2b, 0x02, 0xf4, 0x66, 0x8f, 0x6b, 0xcb, 0x82, 0x6c, 0xad, 0x2b, 0x4b, 0x78,
	0x05, 0xa9, 0x65, 0xc9, 0x8d, 0x75, 0xa6, 0xfd, 0xe2, 0x34, 0xb8, 0xf4, 0xec, 0x16, 0xa2, 0x25,
	0xe0, 0x19, 0x1c, 0xb0, 0x66, 0x59, 0xba, 0x28, 0x89, 0xf0, 0x1f, 0x38, 0x85, 0x94, 0x9c, 0x55,
	0x1b, 0xe5, 0x22, 0x38, 0x10, 0x96, 0x13, 0x2d, 0xad, 0xf8, 0x8e, 0x20, 0xf5, 0x0b, 0x9c, 0x03,
	0x3c, 0xa8, 0x5a, 0x1b, 0x7e, 0x91, 0xaa, 0xc4, 0x61, 0xa0, 0xfc, 0x85, 0x05, 0x7d, 0x34, 0x64,
	0x79, 0x10, 0x56, 0xbc, 0x2d, 0x65, 0xf5, 0xbe, 0xad, 0x90, 0x77, 0xf0, 0x06, 0xba, 0x9b, 0x52,
	0x78, 0x1e, 0x70, 0x7c, 0x4b, 0xaf, 0xbd, 0xdc, 0xcb, 0x14, 0xfe, 0x83, 0xbc, 0x83, 0xd7, 0x90,
	0xde, 0x51, 0x49, 0x4c, 0x18, 0xda, 0x78, 0xe8, 0x1f, 0x01, 0x16, 0xa9, 0x7b, 0x04, 0xb3, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x62, 0x1e, 0xa0, 0x4d, 0x02, 0x00, 0x00,
}
