// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/metatable/schema.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Schema service

type SchemaService interface {
	// 导入YAML
	ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error)
	// 列举
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*SchemaListResponse, error)
	// 删除
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error)
}

type schemaService struct {
	c    client.Client
	name string
}

func NewSchemaService(name string, c client.Client) SchemaService {
	return &schemaService{
		c:    c,
		name: name,
	}
}

func (c *schemaService) ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Schema.ImportYaml", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*SchemaListResponse, error) {
	req := c.c.NewRequest(c.name, "Schema.List", in)
	out := new(SchemaListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Schema.Delete", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Schema service

type SchemaHandler interface {
	// 导入YAML
	ImportYaml(context.Context, *ImportYamlRequest, *BlankResponse) error
	// 列举
	List(context.Context, *ListRequest, *SchemaListResponse) error
	// 删除
	Delete(context.Context, *DeleteRequest, *BlankResponse) error
}

func RegisterSchemaHandler(s server.Server, hdlr SchemaHandler, opts ...server.HandlerOption) error {
	type schema interface {
		ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error
		List(ctx context.Context, in *ListRequest, out *SchemaListResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error
	}
	type Schema struct {
		schema
	}
	h := &schemaHandler{hdlr}
	return s.Handle(s.NewHandler(&Schema{h}, opts...))
}

type schemaHandler struct {
	SchemaHandler
}

func (h *schemaHandler) ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error {
	return h.SchemaHandler.ImportYaml(ctx, in, out)
}

func (h *schemaHandler) List(ctx context.Context, in *ListRequest, out *SchemaListResponse) error {
	return h.SchemaHandler.List(ctx, in, out)
}

func (h *schemaHandler) Delete(ctx context.Context, in *DeleteRequest, out *BlankResponse) error {
	return h.SchemaHandler.Delete(ctx, in, out)
}
