// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metatable/schema.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 规则实体
type RuleEntity struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Element              string   `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleEntity) Reset()         { *m = RuleEntity{} }
func (m *RuleEntity) String() string { return proto.CompactTextString(m) }
func (*RuleEntity) ProtoMessage()    {}
func (*RuleEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9662d2110d3a0dd0, []int{0}
}

func (m *RuleEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleEntity.Unmarshal(m, b)
}
func (m *RuleEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleEntity.Marshal(b, m, deterministic)
}
func (m *RuleEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleEntity.Merge(m, src)
}
func (m *RuleEntity) XXX_Size() int {
	return xxx_messageInfo_RuleEntity.Size(m)
}
func (m *RuleEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RuleEntity proto.InternalMessageInfo

func (m *RuleEntity) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *RuleEntity) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *RuleEntity) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

// 结构实体
type SchemaEntity struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Source               string        `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Rule                 []*RuleEntity `protobuf:"bytes,3,rep,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SchemaEntity) Reset()         { *m = SchemaEntity{} }
func (m *SchemaEntity) String() string { return proto.CompactTextString(m) }
func (*SchemaEntity) ProtoMessage()    {}
func (*SchemaEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9662d2110d3a0dd0, []int{1}
}

func (m *SchemaEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaEntity.Unmarshal(m, b)
}
func (m *SchemaEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaEntity.Marshal(b, m, deterministic)
}
func (m *SchemaEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaEntity.Merge(m, src)
}
func (m *SchemaEntity) XXX_Size() int {
	return xxx_messageInfo_SchemaEntity.Size(m)
}
func (m *SchemaEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaEntity.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaEntity proto.InternalMessageInfo

func (m *SchemaEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SchemaEntity) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SchemaEntity) GetRule() []*RuleEntity {
	if m != nil {
		return m.Rule
	}
	return nil
}

type SchemaListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*SchemaEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SchemaListResponse) Reset()         { *m = SchemaListResponse{} }
func (m *SchemaListResponse) String() string { return proto.CompactTextString(m) }
func (*SchemaListResponse) ProtoMessage()    {}
func (*SchemaListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9662d2110d3a0dd0, []int{2}
}

func (m *SchemaListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaListResponse.Unmarshal(m, b)
}
func (m *SchemaListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaListResponse.Marshal(b, m, deterministic)
}
func (m *SchemaListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaListResponse.Merge(m, src)
}
func (m *SchemaListResponse) XXX_Size() int {
	return xxx_messageInfo_SchemaListResponse.Size(m)
}
func (m *SchemaListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaListResponse proto.InternalMessageInfo

func (m *SchemaListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SchemaListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SchemaListResponse) GetEntity() []*SchemaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*RuleEntity)(nil), "metatable.RuleEntity")
	proto.RegisterType((*SchemaEntity)(nil), "metatable.SchemaEntity")
	proto.RegisterType((*SchemaListResponse)(nil), "metatable.SchemaListResponse")
}

func init() {
	proto.RegisterFile("proto/metatable/schema.proto", fileDescriptor_9662d2110d3a0dd0)
}

var fileDescriptor_9662d2110d3a0dd0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x6e, 0x4c, 0x8c, 0x74, 0xea, 0xc5, 0x41, 0x6b, 0x28, 0x15, 0x4a, 0x4e, 0xf5, 0xd2, 0x42,
	0xbd, 0x2b, 0x88, 0x0a, 0x82, 0x07, 0xd9, 0x9e, 0x3c, 0x6e, 0xdb, 0x91, 0x06, 0x37, 0x49, 0xcd,
	0xce, 0x82, 0xbe, 0x80, 0xef, 0xe7, 0x1b, 0x49, 0x77, 0x37, 0xed, 0x42, 0x2f, 0xde, 0x76, 0xbe,
	0xf9, 0xe6, 0xfb, 0x09, 0x81, 0xe1, 0xa6, 0xa9, 0xb9, 0x9e, 0x96, 0xc4, 0x92, 0xe5, 0x42, 0xd1,
	0x54, 0x2f, 0xd7, 0x54, 0xca, 0x89, 0x85, 0xb1, 0xbb, 0xc3, 0x07, 0x87, 0xc4, 0xb5, 0x6c, 0x68,
	0xe5, 0x88, 0xf9, 0x2b, 0x80, 0x30, 0x8a, 0x1e, 0x2b, 0x2e, 0xf8, 0x1b, 0xcf, 0xe1, 0xf8, 0xbd,
	0x20, 0xb5, 0xca, 0xa2, 0x51, 0x34, 0xee, 0x0a, 0x37, 0x20, 0x42, 0xc2, 0xf4, 0xc5, 0xd9, 0x91,
	0x05, 0xed, 0x1b, 0x33, 0x38, 0x21, 0x45, 0x25, 0x55, 0x9c, 0xc5, 0x16, 0x6e, 0xc7, 0x9c, 0xe0,
	0x74, 0x6e, 0xa3, 0x78, 0x4d, 0x84, 0xc4, 0x98, 0xa2, 0x95, 0xb4, 0x6f, 0xec, 0x43, 0xaa, 0x6b,
	0xd3, 0x2c, 0xc9, 0x6b, 0xfa, 0x09, 0xaf, 0x21, 0x69, 0x8c, 0xa2, 0x2c, 0x1e, 0xc5, 0xe3, 0xde,
	0xec, 0x62, 0xb2, 0x0b, 0x3d, 0xd9, 0x87, 0x14, 0x96, 0x92, 0xff, 0x44, 0x80, 0xce, 0xe7, 0xa5,
	0xd0, 0x2c, 0x48, 0x6f, 0xea, 0x4a, 0x6f, 0x15, 0x52, 0xcd, 0x92, 0x8d, 0xb6, 0x7e, 0xbd, 0xd9,
	0x59, 0xa0, 0x31, 0xb7, 0x0b, 0xe1, 0x09, 0xdb, 0xb2, 0x5c, 0xb3, 0x54, 0x36, 0x43, 0x2c, 0xdc,
	0x80, 0x53, 0x48, 0xc9, 0xfa, 0xf8, 0x10, 0x97, 0xa1, 0x40, 0xd0, 0x4b, 0x78, 0xda, 0xec, 0x37,
	0x82, 0xd4, 0x2d, 0xf0, 0x09, 0xe0, 0xb9, 0xdc, 0xd4, 0x0d, 0xbf, 0xc9, 0x52, 0xe1, 0x30, 0xb8,
	0xdc, 0xc3, 0x82, 0x3e, 0x0d, 0x69, 0x1e, 0x64, 0xc1, 0xf6, 0x5e, 0xc9, 0xea, 0xa3, 0xad, 0x90,
	0x77, 0xf0, 0x0e, 0x92, 0x6d, 0x29, 0xec, 0x07, 0x1c, 0xd7, 0xd2, 0xdd, 0x5e, 0x1d, 0x64, 0x0a,
	0xbf, 0x41, 0xde, 0xc1, 0x5b, 0x48, 0x1f, 0x48, 0x11, 0x13, 0x86, 0x36, 0x0e, 0xfa, 0x47, 0x80,
	0x45, 0x6a, 0x7f, 0x8e, 0x9b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0xde, 0x76, 0x27, 0x65,
	0x02, 0x00, 0x00,
}
