// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metatable/shared.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 导入YAML的请求
type ImportYamlRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportYamlRequest) Reset()         { *m = ImportYamlRequest{} }
func (m *ImportYamlRequest) String() string { return proto.CompactTextString(m) }
func (*ImportYamlRequest) ProtoMessage()    {}
func (*ImportYamlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{2}
}

func (m *ImportYamlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportYamlRequest.Unmarshal(m, b)
}
func (m *ImportYamlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportYamlRequest.Marshal(b, m, deterministic)
}
func (m *ImportYamlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportYamlRequest.Merge(m, src)
}
func (m *ImportYamlRequest) XXX_Size() int {
	return xxx_messageInfo_ImportYamlRequest.Size(m)
}
func (m *ImportYamlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportYamlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportYamlRequest proto.InternalMessageInfo

func (m *ImportYamlRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 列举的请求
type ListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 查找的请求
type FindRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{4}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 删除的请求
type DeleteRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab64313c6844599d, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "metatable.Status")
	proto.RegisterType((*BlankResponse)(nil), "metatable.BlankResponse")
	proto.RegisterType((*ImportYamlRequest)(nil), "metatable.ImportYamlRequest")
	proto.RegisterType((*ListRequest)(nil), "metatable.ListRequest")
	proto.RegisterType((*FindRequest)(nil), "metatable.FindRequest")
	proto.RegisterType((*DeleteRequest)(nil), "metatable.DeleteRequest")
}

func init() {
	proto.RegisterFile("proto/metatable/shared.proto", fileDescriptor_ab64313c6844599d)
}

var fileDescriptor_ab64313c6844599d = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x6d, 0x23, 0x99, 0xd0, 0x43, 0x17, 0x91, 0x1c, 0x3c, 0xd4, 0xf5, 0x52, 0x0f,
	0xa6, 0xa0, 0xe0, 0x41, 0x6f, 0x22, 0x82, 0xe0, 0x69, 0x3d, 0x79, 0xdc, 0x26, 0x53, 0x0d, 0xee,
	0x9f, 0x98, 0x99, 0xfd, 0xfe, 0xd2, 0x4d, 0xb6, 0xf4, 0xf6, 0xde, 0xe3, 0xb7, 0xef, 0x2d, 0x03,
	0x57, 0xfd, 0xe0, 0xd9, 0x6f, 0x2d, 0xb2, 0x66, 0xbd, 0x33, 0xb8, 0xa5, 0x1f, 0x3d, 0x60, 0x5b,
	0xc7, 0x58, 0x14, 0xc7, 0x5c, 0x3e, 0x42, 0xfe, 0xc9, 0x9a, 0x03, 0x09, 0x01, 0xf3, 0xc6, 0xb7,
	0x58, 0x65, 0xeb, 0x6c, 0xb3, 0x50, 0x51, 0x8b, 0x0a, 0xce, 0x2d, 0x12, 0xe9, 0x6f, 0xac, 0xce,
	0xd6, 0xd9, 0xa6, 0x50, 0xc9, 0xca, 0x27, 0x58, 0xbe, 0x18, 0xed, 0x7e, 0x15, 0x52, 0xef, 0x1d,
	0xa1, 0xb8, 0x85, 0x9c, 0x62, 0x51, 0x2c, 0x28, 0xef, 0x57, 0xf5, 0x71, 0xa4, 0x1e, 0x17, 0xd4,
	0x04, 0xc8, 0x3b, 0x58, 0xbd, 0xdb, 0xde, 0x0f, 0xfc, 0xa5, 0xad, 0x51, 0xf8, 0x17, 0x90, 0xf8,
	0x30, 0xd5, 0x78, 0xc7, 0xe8, 0x38, 0x16, 0x14, 0x2a, 0x59, 0xf9, 0x0c, 0xe5, 0x47, 0x47, 0x9c,
	0xc0, 0x4b, 0xc8, 0xfd, 0x7e, 0x4f, 0x38, 0x72, 0x33, 0x35, 0x39, 0x71, 0x01, 0x8b, 0xc6, 0x07,
	0xc7, 0xf1, 0xa7, 0x33, 0x35, 0x1a, 0x79, 0x0d, 0xe5, 0x5b, 0xe7, 0xda, 0xf4, 0x58, 0xc0, 0xdc,
	0x69, 0x8b, 0xd3, 0x44, 0xd4, 0xf2, 0x06, 0x96, 0xaf, 0x68, 0x90, 0xf1, 0x04, 0x0a, 0xa1, 0x6b,
	0x13, 0x74, 0xd0, 0xbb, 0x3c, 0x5e, 0xee, 0xe1, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x37, 0x7b, 0xb3,
	0xf1, 0x59, 0x01, 0x00, 0x00,
}
