// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metatable/source.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 实体
type SourceEntity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Expression           string   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceEntity) Reset()         { *m = SourceEntity{} }
func (m *SourceEntity) String() string { return proto.CompactTextString(m) }
func (*SourceEntity) ProtoMessage()    {}
func (*SourceEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_8647216acc740522, []int{0}
}

func (m *SourceEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceEntity.Unmarshal(m, b)
}
func (m *SourceEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceEntity.Marshal(b, m, deterministic)
}
func (m *SourceEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceEntity.Merge(m, src)
}
func (m *SourceEntity) XXX_Size() int {
	return xxx_messageInfo_SourceEntity.Size(m)
}
func (m *SourceEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceEntity.DiscardUnknown(m)
}

var xxx_messageInfo_SourceEntity proto.InternalMessageInfo

func (m *SourceEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SourceEntity) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SourceEntity) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type SourceListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*SourceEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SourceListResponse) Reset()         { *m = SourceListResponse{} }
func (m *SourceListResponse) String() string { return proto.CompactTextString(m) }
func (*SourceListResponse) ProtoMessage()    {}
func (*SourceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8647216acc740522, []int{1}
}

func (m *SourceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceListResponse.Unmarshal(m, b)
}
func (m *SourceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceListResponse.Marshal(b, m, deterministic)
}
func (m *SourceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceListResponse.Merge(m, src)
}
func (m *SourceListResponse) XXX_Size() int {
	return xxx_messageInfo_SourceListResponse.Size(m)
}
func (m *SourceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SourceListResponse proto.InternalMessageInfo

func (m *SourceListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SourceListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SourceListResponse) GetEntity() []*SourceEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceEntity)(nil), "metatable.SourceEntity")
	proto.RegisterType((*SourceListResponse)(nil), "metatable.SourceListResponse")
}

func init() {
	proto.RegisterFile("proto/metatable/source.proto", fileDescriptor_8647216acc740522)
}

var fileDescriptor_8647216acc740522 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x4c, 0x8d, 0x74, 0xea, 0xc5, 0x41, 0x74, 0x29, 0x55, 0x4a, 0x4e, 0xf5, 0x92, 0x40,
	0xfc, 0x00, 0x41, 0x50, 0x10, 0x3c, 0x6d, 0x4f, 0x82, 0x97, 0xad, 0x19, 0x30, 0x98, 0x64, 0x63,
	0x76, 0x02, 0xfa, 0x03, 0xde, 0xfd, 0x63, 0xe9, 0x6c, 0x5b, 0x17, 0x7a, 0x9b, 0x79, 0xef, 0xcd,
	0xcc, 0x7b, 0xbb, 0x30, 0xef, 0x7a, 0xcb, 0x36, 0x6f, 0x88, 0x0d, 0x9b, 0x75, 0x4d, 0xb9, 0xb3,
	0x43, 0xff, 0x46, 0x99, 0xc0, 0x38, 0xd9, 0xe3, 0xb3, 0x43, 0xe1, 0xbb, 0xe9, 0xa9, 0xf4, 0xc2,
	0xf4, 0x15, 0x4e, 0x57, 0x32, 0xf8, 0xd0, 0x72, 0xc5, 0xdf, 0x88, 0x30, 0x6e, 0x4d, 0x43, 0x2a,
	0x5a, 0x44, 0xcb, 0x89, 0x96, 0x1a, 0x15, 0x9c, 0x98, 0xb2, 0xec, 0xc9, 0x39, 0x75, 0x24, 0xf0,
	0xae, 0xc5, 0x6b, 0x00, 0xfa, 0xea, 0x36, 0x65, 0x65, 0x5b, 0x15, 0x0b, 0x19, 0x20, 0xe9, 0x4f,
	0x04, 0xe8, 0xd7, 0x3f, 0x57, 0x8e, 0x35, 0xb9, 0xce, 0xb6, 0x8e, 0xf0, 0x06, 0x12, 0xc7, 0x86,
	0x07, 0x27, 0x67, 0xa6, 0xc5, 0x59, 0xb6, 0x77, 0x97, 0xad, 0x84, 0xd0, 0x5b, 0x01, 0x9e, 0xc3,
	0x31, 0x5b, 0x36, 0xb5, 0x5c, 0x8e, 0xb5, 0x6f, 0x30, 0x87, 0x84, 0xc4, 0xaf, 0x8a, 0x17, 0xf1,
	0x72, 0x5a, 0x5c, 0x86, 0x0b, 0x82, 0x38, 0x7a, 0x2b, 0x2b, 0x7e, 0x23, 0x48, 0x3c, 0x81, 0x8f,
	0x00, 0x4f, 0x4d, 0x67, 0x7b, 0x7e, 0x31, 0x4d, 0x8d, 0xf3, 0x60, 0xf2, 0x1f, 0xd6, 0xf4, 0x39,
	0x90, 0xe3, 0x99, 0x0a, 0xd8, 0xfb, 0xda, 0xb4, 0x1f, 0xbb, 0x08, 0xe9, 0x08, 0xef, 0x60, 0xbc,
	0x09, 0x85, 0x17, 0x81, 0xc6, 0xa7, 0xf4, 0xb3, 0x57, 0x07, 0x9e, 0xc2, 0x37, 0x48, 0x47, 0xeb,
	0x44, 0x7e, 0xe0, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x00, 0xf4, 0x62, 0x74, 0xca, 0x01, 0x00,
	0x00,
}
