// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/metatable/vocabulary.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Vocabulary service

type VocabularyService interface {
	// 导入YAML
	ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error)
	// 列举
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*VocabularyListResponse, error)
	// 查找
	Find(ctx context.Context, in *FindRequest, opts ...client.CallOption) (*VocabularyFindResponse, error)
}

type vocabularyService struct {
	c    client.Client
	name string
}

func NewVocabularyService(name string, c client.Client) VocabularyService {
	return &vocabularyService{
		c:    c,
		name: name,
	}
}

func (c *vocabularyService) ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*BlankResponse, error) {
	req := c.c.NewRequest(c.name, "Vocabulary.ImportYaml", in)
	out := new(BlankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabularyService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*VocabularyListResponse, error) {
	req := c.c.NewRequest(c.name, "Vocabulary.List", in)
	out := new(VocabularyListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabularyService) Find(ctx context.Context, in *FindRequest, opts ...client.CallOption) (*VocabularyFindResponse, error) {
	req := c.c.NewRequest(c.name, "Vocabulary.Find", in)
	out := new(VocabularyFindResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Vocabulary service

type VocabularyHandler interface {
	// 导入YAML
	ImportYaml(context.Context, *ImportYamlRequest, *BlankResponse) error
	// 列举
	List(context.Context, *ListRequest, *VocabularyListResponse) error
	// 查找
	Find(context.Context, *FindRequest, *VocabularyFindResponse) error
}

func RegisterVocabularyHandler(s server.Server, hdlr VocabularyHandler, opts ...server.HandlerOption) error {
	type vocabulary interface {
		ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error
		List(ctx context.Context, in *ListRequest, out *VocabularyListResponse) error
		Find(ctx context.Context, in *FindRequest, out *VocabularyFindResponse) error
	}
	type Vocabulary struct {
		vocabulary
	}
	h := &vocabularyHandler{hdlr}
	return s.Handle(s.NewHandler(&Vocabulary{h}, opts...))
}

type vocabularyHandler struct {
	VocabularyHandler
}

func (h *vocabularyHandler) ImportYaml(ctx context.Context, in *ImportYamlRequest, out *BlankResponse) error {
	return h.VocabularyHandler.ImportYaml(ctx, in, out)
}

func (h *vocabularyHandler) List(ctx context.Context, in *ListRequest, out *VocabularyListResponse) error {
	return h.VocabularyHandler.List(ctx, in, out)
}

func (h *vocabularyHandler) Find(ctx context.Context, in *FindRequest, out *VocabularyFindResponse) error {
	return h.VocabularyHandler.Find(ctx, in, out)
}
