// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/metatable/vocabulary.proto

package metatable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Vocabulary service

type VocabularyService interface {
	// 导入YAML
	ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*ImportResponse, error)
}

type vocabularyService struct {
	c    client.Client
	name string
}

func NewVocabularyService(name string, c client.Client) VocabularyService {
	return &vocabularyService{
		c:    c,
		name: name,
	}
}

func (c *vocabularyService) ImportYaml(ctx context.Context, in *ImportYamlRequest, opts ...client.CallOption) (*ImportResponse, error) {
	req := c.c.NewRequest(c.name, "Vocabulary.ImportYaml", in)
	out := new(ImportResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Vocabulary service

type VocabularyHandler interface {
	// 导入YAML
	ImportYaml(context.Context, *ImportYamlRequest, *ImportResponse) error
}

func RegisterVocabularyHandler(s server.Server, hdlr VocabularyHandler, opts ...server.HandlerOption) error {
	type vocabulary interface {
		ImportYaml(ctx context.Context, in *ImportYamlRequest, out *ImportResponse) error
	}
	type Vocabulary struct {
		vocabulary
	}
	h := &vocabularyHandler{hdlr}
	return s.Handle(s.NewHandler(&Vocabulary{h}, opts...))
}

type vocabularyHandler struct {
	VocabularyHandler
}

func (h *vocabularyHandler) ImportYaml(ctx context.Context, in *ImportYamlRequest, out *ImportResponse) error {
	return h.VocabularyHandler.ImportYaml(ctx, in, out)
}
